CREATE DATABASE IF NOT EXISTS edv1;


USE edv1;

CREATE TABLE IF NOT EXISTS studenten
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    anrede VARCHAR(30) NOT NULL,
    vorname VARCHAR(30) NOT NULL,
    nachname VARCHAR(30) NOT NULL,
    ort VARCHAR(50) NOT NULL 
)DEFAULT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';